version: '3.8'

services:
  coturn:
    image: coturn/coturn:latest
    container_name: gramothi-turn-server
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-65535:49152-65535/udp"
    environment:
      - TURN_USERNAME=gramothi
      - TURN_PASSWORD=gramothi123
      - TURN_REALM=gramothi.local
    command: >
      --listening-port=3478
      --tls-listening-port=5349
      --listening-ip=0.0.0.0
      --external-ip=auto-detect
      --realm=gramothi.local
      --server-name=gramothi.local
      --user=gramothi:gramothi123
      --no-tlsv1
      --no-tlsv1_1
      --no-tlsv1_2
      --no-tlsv1_3
      --no-dtls
      --no-tls
      --log-file=stdout
      --verbose
      --fingerprint
      --lt-cred-mech
      --no-multicast-peers
      --no-cli
      --no-tlsv1
      --no-tlsv1_1
      --no-tlsv1_2
      --no-tlsv1_3
      --no-dtls
      --no-tls
      --log-file=stdout
      --verbose
      --fingerprint
      --lt-cred-mech
      --no-multicast-peers
      --no-cli
    restart: unless-stopped
    networks:
      - gramothi-network

networks:
  gramothi-network:
    driver: bridge
